project="gateway"
module="gateway-data"
remotehost="root@10.8.15.82"
dir="/data/app/${module}"
app="gateway-data-1.0.0-SNAPSHOT.jar"
remoteDir="${remotehost}:${repository}/${project}/${module}/target"
